my_string = input('Введите произвольный текст: ')
print('В Вашем тексте',len(my_string), 'символов, включая пробелы.')
print('Ваш текст в верхнем регистре:',my_string.upper())
print('Ваш текст в нижнем регистре:',my_string.lower())
print('Ваш текст без пробелов:',my_string.replace(' ', ''))
print('Первый символ Вашего текста:',my_string[0])
print('Последний символ Вашего текста:',my_string[-1])